db/generate:
	@echo "Generating database migrations..."
	npx drizzle-kit generate
	
db/migrate:
	@echo "Running database migrations..."
	npx drizzle-kit migrate

db/studio:
	@echo "Starting database studio..."
	npx drizzle-kit studio